# TREAT CHARGE / HOME TO EARTH copy (Dan, 2026-10-08): label only + no death language + no eyewear.
# Applies the new values for these keys in every language block of src/i18n.ts.
import re, sys
T = {
'en': dict(
 shade_charge='TREAT CHARGE',
 title_dodge_p='Dodge the glare. Keep your treat charge up.',
 title_dodge_l='Dodge glare · keep treat charge up',
 title_collect='Collect treats — keep TREAT CHARGE up',
 desk_dodge='Dodge the glare. Keep your treat charge up.',
 fl_shade='+TREATS',
 fl_eaten='HOME TO EARTH! PACK GROWS',
 tut2_a='Treat bowls refill your treat charge',
 tut2_b='TREAT CHARGE runs out = a dog flies home to Earth for more treats',
 tut2_b_cats='TREAT CHARGE runs out = a cat flies home to Earth for more treats',
 tut2_b_together='TREAT CHARGE runs out = a pet flies home to Earth for more treats',
 tut3_c='You start with 4 dogs: when all fly home to Earth, the trip ends',
 tut3_c_cats='You start with 4 cats: when all fly home to Earth, the trip ends',
 tut3_c_together='You start with 4 pets: when all fly home to Earth, the trip ends',
 tut3_d='Treats refill it, gates fill it; {b} burns it',
 dom_clone_line='Level eleven. A tip of the hat to Weird Al Yankovic.',
 sr_gameover='Everyone flew home to Earth'),
'es': dict(
 shade_charge='CARGA DE PREMIOS',
 title_dodge_p='Esquiva el resplandor. Mantén la carga de premios.',
 title_dodge_l='Esquiva el brillo · mantén los premios',
 title_collect='Junta premios — mantén la CARGA DE PREMIOS',
 desk_dodge='Esquiva el resplandor. Mantén tu carga de premios.',
 fl_shade='+PREMIOS',
 fl_eaten='¡A CASA, A LA TIERRA! LA MANADA CRECE',
 tut2_a='Los platos de premios recargan tu carga',
 tut2_b='Sin CARGA DE PREMIOS = un perro vuela a la Tierra por más premios',
 tut2_b_cats='Sin CARGA DE PREMIOS = un gato vuela a la Tierra por más premios',
 tut2_b_together='Sin CARGA DE PREMIOS = una mascota vuela a la Tierra por más premios',
 tut3_c='Empiezas con 4 perros: cuando todos vuelven a la Tierra, termina el viaje',
 tut3_c_cats='Empiezas con 4 gatos: cuando todos vuelven a la Tierra, termina el viaje',
 tut3_c_together='Empiezas con 4 mascotas: cuando todas vuelven a la Tierra, termina el viaje',
 tut3_d='Premios recargan, aros llenan; {b} gasta',
 dom_clone_line='Nivel once. Nos quitamos el sombrero ante Weird Al Yankovic.',
 sr_gameover='Todos volaron a casa, a la Tierra'),
'vi': dict(
 shade_charge='PIN BÁNH THƯỞNG',
 title_dodge_p='Né ánh chói. Giữ pin bánh thưởng luôn đầy.',
 title_dodge_l='Né ánh chói · giữ bánh thưởng đầy',
 title_collect='Nhặt bánh thưởng — giữ PIN BÁNH THƯỞNG',
 desk_dodge='Né ánh chói. Giữ pin bánh thưởng của bạn luôn đầy.',
 fl_shade='+BÁNH THƯỞNG',
 fl_eaten='VỀ NHÀ, VỀ TRÁI ĐẤT! ĐÀN LỚN HƠN',
 tut2_a='Bát bánh thưởng nạp lại pin',
 tut2_b='Hết PIN BÁNH THƯỞNG = một chú chó bay về Trái Đất lấy thêm bánh',
 tut2_b_cats='Hết PIN BÁNH THƯỞNG = một chú mèo bay về Trái Đất lấy thêm bánh',
 tut2_b_together='Hết PIN BÁNH THƯỞNG = một thú cưng bay về Trái Đất lấy thêm bánh',
 tut3_c='Bạn bắt đầu với 4 chú chó: khi tất cả bay về Trái Đất, chuyến đi kết thúc',
 tut3_c_cats='Bạn bắt đầu với 4 chú mèo: khi tất cả bay về Trái Đất, chuyến đi kết thúc',
 tut3_c_together='Bạn bắt đầu với 4 thú cưng: khi tất cả bay về Trái Đất, chuyến đi kết thúc',
 tut3_d='Bánh thưởng nạp pin, cổng nạp đầy; {b} đốt pin',
 dom_clone_line='Cấp mười một. Ngả mũ chào Weird Al Yankovic.',
 sr_gameover='Cả đàn đã bay về Trái Đất'),
'zh': dict(
 shade_charge='零食电量',
 title_dodge_p='躲开强光。保持零食电量。',
 title_dodge_l='躲开强光 · 保持零食电量',
 title_collect='收集零食 — 保持零食电量',
 desk_dodge='躲开强光。保持你的零食电量。',
 fl_shade='+零食',
 fl_eaten='回地球啦！队伍变大',
 tut2_a='零食碗为零食电量充能',
 tut2_b='零食电量用完 = 一只狗飞回地球拿零食',
 tut2_b_cats='零食电量用完 = 一只猫飞回地球拿零食',
 tut2_b_together='零食电量用完 = 一只宠物飞回地球拿零食',
 tut3_c='开局有 4 只狗：全部飞回地球时，旅程结束',
 tut3_c_cats='开局有 4 只猫：全部飞回地球时，旅程结束',
 tut3_c_together='开局有 4 只宠物：全部飞回地球时，旅程结束',
 tut3_d='零食充能，光门加满；{b} 消耗',
 dom_clone_line='第十一关。向 Weird Al Yankovic 脱帽致敬。',
 sr_gameover='大家都飞回地球了'),
'fr': dict(
 shade_charge='CHARGE FRIANDISES',
 title_dodge_p='Évite l’éclat. Garde ta charge de friandises.',
 title_dodge_l='Évite l’éclat · garde tes friandises',
 title_collect='Ramasse des friandises — garde la CHARGE FRIANDISES',
 desk_dodge='Évite l’éclat. Garde ta charge de friandises.',
 fl_shade='+FRIANDISES',
 fl_eaten='RETOUR SUR TERRE ! LA MEUTE GRANDIT',
 tut2_a='Les bols de friandises rechargent ta charge',
 tut2_b='CHARGE FRIANDISES à zéro = un chien rentre sur Terre chercher des friandises',
 tut2_b_cats='CHARGE FRIANDISES à zéro = un chat rentre sur Terre chercher des friandises',
 tut2_b_together='CHARGE FRIANDISES à zéro = un animal rentre sur Terre chercher des friandises',
 tut3_c='Tu commences avec 4 chiens : quand tous rentrent sur Terre, le voyage s’arrête',
 tut3_c_cats='Tu commences avec 4 chats : quand tous rentrent sur Terre, le voyage s’arrête',
 tut3_c_together='Tu commences avec 4 animaux : quand tous rentrent sur Terre, le voyage s’arrête',
 tut3_d='Les friandises rechargent, les portails remplissent ; {b} consomme',
 dom_clone_line='Niveau onze. Un coup de chapeau à Weird Al Yankovic.',
 sr_gameover='Tout le monde est rentré sur Terre'),
'de': dict(
 shade_charge='LECKERLI-LADUNG',
 title_dodge_p='Weich dem Licht aus. Halte die Leckerli-Ladung oben.',
 title_dodge_l='Licht ausweichen · Leckerlis halten',
 title_collect='Leckerlis sammeln — LECKERLI-LADUNG halten',
 desk_dodge='Weich dem Licht aus. Halte deine Leckerli-Ladung oben.',
 fl_shade='+LECKERLIS',
 fl_eaten='HEIM ZUR ERDE! RUDEL WÄCHST',
 tut2_a='Leckerli-Näpfe füllen deine Ladung auf',
 tut2_b='LECKERLI-LADUNG leer = ein Hund fliegt heim zur Erde, neue Leckerlis holen',
 tut2_b_cats='LECKERLI-LADUNG leer = eine Katze fliegt heim zur Erde, neue Leckerlis holen',
 tut2_b_together='LECKERLI-LADUNG leer = ein Tier fliegt heim zur Erde, neue Leckerlis holen',
 tut3_c='Du startest mit 4 Hunden: Wenn alle heim zur Erde fliegen, endet die Reise',
 tut3_c_cats='Du startest mit 4 Katzen: Wenn alle heim zur Erde fliegen, endet die Reise',
 tut3_c_together='Du startest mit 4 Tieren: Wenn alle heim zur Erde fliegen, endet die Reise',
 tut3_d='Leckerlis füllen auf, Tore füllen es; {b} verbraucht es',
 dom_clone_line='Level elf. Hut ab vor Weird Al Yankovic.',
 sr_gameover='Alle sind heim zur Erde geflogen'),
'pt': dict(
 shade_charge='CARGA DE PETISCOS',
 title_dodge_p='Desvie do clarão. Mantenha a carga de petiscos.',
 title_dodge_l='Desvie do clarão · mantenha os petiscos',
 title_collect='Pegue petiscos — mantenha a CARGA DE PETISCOS',
 desk_dodge='Desvie do clarão. Mantenha sua carga de petiscos.',
 fl_shade='+PETISCOS',
 fl_eaten='DE VOLTA À TERRA! A MATILHA CRESCE',
 tut2_a='Potes de petiscos recarregam sua carga',
 tut2_b='CARGA DE PETISCOS zerar = um cão voa para a Terra buscar petiscos',
 tut2_b_cats='CARGA DE PETISCOS zerar = um gato voa para a Terra buscar petiscos',
 tut2_b_together='CARGA DE PETISCOS zerar = um pet voa para a Terra buscar petiscos',
 tut3_c='Você começa com 4 cães: quando todos voltam à Terra, a viagem termina',
 tut3_c_cats='Você começa com 4 gatos: quando todos voltam à Terra, a viagem termina',
 tut3_c_together='Você começa com 4 pets: quando todos voltam à Terra, a viagem termina',
 tut3_d='Petiscos recarregam, portais enchem; {b} gasta',
 dom_clone_line='Nível onze. Tiramos o chapéu para Weird Al Yankovic.',
 sr_gameover='Todos voaram de volta para a Terra'),
'it': dict(
 shade_charge='CARICA BOCCONCINI',
 title_dodge_p='Schiva il bagliore. Tieni alta la carica bocconcini.',
 title_dodge_l='Schiva il bagliore · tieni i bocconcini',
 title_collect='Raccogli bocconcini — tieni la CARICA BOCCONCINI',
 desk_dodge='Schiva il bagliore. Tieni alta la tua carica bocconcini.',
 fl_shade='+BOCCONCINI',
 fl_eaten='A CASA SULLA TERRA! IL BRANCO CRESCE',
 tut2_a='Le ciotole di bocconcini ricaricano la carica',
 tut2_b='CARICA BOCCONCINI a zero = un cane torna sulla Terra a prendere bocconcini',
 tut2_b_cats='CARICA BOCCONCINI a zero = un gatto torna sulla Terra a prendere bocconcini',
 tut2_b_together='CARICA BOCCONCINI a zero = un animale torna sulla Terra a prendere bocconcini',
 tut3_c='Parti con 4 cani: quando tornano tutti sulla Terra, il viaggio finisce',
 tut3_c_cats='Parti con 4 gatti: quando tornano tutti sulla Terra, il viaggio finisce',
 tut3_c_together='Parti con 4 animali: quando tornano tutti sulla Terra, il viaggio finisce',
 tut3_d='I bocconcini ricaricano, i portali riempiono; {b} consuma',
 dom_clone_line='Livello undici. Giù il cappello per Weird Al Yankovic.',
 sr_gameover='Tutti sono tornati a casa sulla Terra'),
'nl': dict(
 shade_charge='SNOEPJESLADING',
 title_dodge_p='Ontwijk de schittering. Houd je snoepjeslading op peil.',
 title_dodge_l='Ontwijk de gloed · houd snoepjes op peil',
 title_collect='Verzamel snoepjes — houd SNOEPJESLADING op peil',
 desk_dodge='Ontwijk de schittering. Houd je snoepjeslading op peil.',
 fl_shade='+SNOEPJES',
 fl_eaten='NAAR HUIS, NAAR DE AARDE! DE ROEDEL GROEIT',
 tut2_a='Snoepjesbakjes vullen je lading aan',
 tut2_b='SNOEPJESLADING op = een hond vliegt naar de Aarde voor meer snoepjes',
 tut2_b_cats='SNOEPJESLADING op = een kat vliegt naar de Aarde voor meer snoepjes',
 tut2_b_together='SNOEPJESLADING op = een huisdier vliegt naar de Aarde voor meer snoepjes',
 tut3_c='Je begint met 4 honden: als ze allemaal naar de Aarde vliegen, stopt de reis',
 tut3_c_cats='Je begint met 4 katten: als ze allemaal naar de Aarde vliegen, stopt de reis',
 tut3_c_together='Je begint met 4 huisdieren: als ze allemaal naar de Aarde vliegen, stopt de reis',
 tut3_d='Snoepjes vullen aan, poorten vullen; {b} verbruikt',
 dom_clone_line='Level elf. Petje af voor Weird Al Yankovic.',
 sr_gameover='Iedereen is naar huis gevlogen, naar de Aarde'),
'pl': dict(
 shade_charge='ŁADUNEK SMAKOŁYKÓW',
 title_dodge_p='Unikaj blasku. Trzymaj ładunek smakołyków.',
 title_dodge_l='Unikaj blasku · trzymaj smakołyki',
 title_collect='Zbieraj smakołyki — trzymaj ŁADUNEK SMAKOŁYKÓW',
 desk_dodge='Unikaj blasku. Trzymaj swój ładunek smakołyków.',
 fl_shade='+SMAKOŁYKI',
 fl_eaten='DO DOMU, NA ZIEMIĘ! STADO ROŚNIE',
 tut2_a='Miski smakołyków ładują twój ładunek',
 tut2_b='ŁADUNEK SMAKOŁYKÓW się kończy = pies leci na Ziemię po smakołyki',
 tut2_b_cats='ŁADUNEK SMAKOŁYKÓW się kończy = kot leci na Ziemię po smakołyki',
 tut2_b_together='ŁADUNEK SMAKOŁYKÓW się kończy = zwierzak leci na Ziemię po smakołyki',
 tut3_c='Zaczynasz z 4 psami: gdy wszystkie polecą na Ziemię, podróż się kończy',
 tut3_c_cats='Zaczynasz z 4 kotami: gdy wszystkie polecą na Ziemię, podróż się kończy',
 tut3_c_together='Zaczynasz z 4 zwierzakami: gdy wszystkie polecą na Ziemię, podróż się kończy',
 tut3_d='Smakołyki ładują, bramy napełniają; {b} zużywa',
 dom_clone_line='Poziom jedenasty. Czapki z głów przed Weird Al Yankovic.',
 sr_gameover='Wszyscy polecieli do domu, na Ziemię'),
'tr': dict(
 shade_charge='ÖDÜL MAMASI ŞARJI',
 title_dodge_p='Parıltıdan kaç. Ödül maması şarjını dolu tut.',
 title_dodge_l='Parıltıdan kaç · ödül mamasını tut',
 title_collect='Ödül maması topla — ÖDÜL MAMASI ŞARJINI tut',
 desk_dodge='Parıltıdan kaç. Ödül maması şarjını dolu tut.',
 fl_shade='+ÖDÜL MAMASI',
 fl_eaten='EVE, DÜNYAYA! SÜRÜ BÜYÜYOR',
 tut2_a='Ödül kâseleri şarjını doldurur',
 tut2_b='ÖDÜL MAMASI ŞARJI biterse = bir köpek ödül için Dünyaya uçar',
 tut2_b_cats='ÖDÜL MAMASI ŞARJI biterse = bir kedi ödül için Dünyaya uçar',
 tut2_b_together='ÖDÜL MAMASI ŞARJI biterse = bir dostun ödül için Dünyaya uçar',
 tut3_c='4 köpekle başlarsın: hepsi Dünyaya dönünce yolculuk biter',
 tut3_c_cats='4 kediyle başlarsın: hepsi Dünyaya dönünce yolculuk biter',
 tut3_c_together='4 dostla başlarsın: hepsi Dünyaya dönünce yolculuk biter',
 tut3_d='Ödüller doldurur, kapılar doldurur; {b} harcar',
 dom_clone_line='On birinci seviye. Weird Al Yankovic’e şapka çıkarıyoruz.',
 sr_gameover='Herkes eve, Dünyaya uçtu'),
'id': dict(
 shade_charge='DAYA CAMILAN',
 title_dodge_p='Hindari silau. Jaga daya camilan tetap penuh.',
 title_dodge_l='Hindari silau · jaga camilan',
 title_collect='Kumpulkan camilan — jaga DAYA CAMILAN',
 desk_dodge='Hindari silau. Jaga daya camilanmu tetap penuh.',
 fl_shade='+CAMILAN',
 fl_eaten='PULANG KE BUMI! KAWANAN TUMBUH',
 tut2_a='Mangkuk camilan mengisi ulang dayamu',
 tut2_b='DAYA CAMILAN habis = seekor anjing terbang pulang ke Bumi cari camilan',
 tut2_b_cats='DAYA CAMILAN habis = seekor kucing terbang pulang ke Bumi cari camilan',
 tut2_b_together='DAYA CAMILAN habis = seekor hewan terbang pulang ke Bumi cari camilan',
 tut3_c='Kamu mulai dengan 4 anjing: saat semua pulang ke Bumi, perjalanan selesai',
 tut3_c_cats='Kamu mulai dengan 4 kucing: saat semua pulang ke Bumi, perjalanan selesai',
 tut3_c_together='Kamu mulai dengan 4 hewan: saat semua pulang ke Bumi, perjalanan selesai',
 tut3_d='Camilan mengisi, gerbang memenuhi; {b} menghabiskan',
 dom_clone_line='Level sebelas. Angkat topi untuk Weird Al Yankovic.',
 sr_gameover='Semua terbang pulang ke Bumi'),
'fil': dict(
 shade_charge='TREAT CHARGE',
 title_dodge_p='Iwasan ang silaw. Panatilihing puno ang treat charge.',
 title_dodge_l='Iwasan ang silaw · panatilihin ang treats',
 title_collect='Mangolekta ng treats — panatilihin ang TREAT CHARGE',
 desk_dodge='Iwasan ang silaw. Panatilihing puno ang iyong treat charge.',
 fl_shade='+TREATS',
 fl_eaten='UWI SA EARTH! LUMALAKI ANG GRUPO',
 tut2_a='Pinupuno ng mga mangkok ng treats ang iyong charge',
 tut2_b='Ubos ang TREAT CHARGE = lilipad pauwi sa Earth ang isang aso para sa treats',
 tut2_b_cats='Ubos ang TREAT CHARGE = lilipad pauwi sa Earth ang isang pusa para sa treats',
 tut2_b_together='Ubos ang TREAT CHARGE = lilipad pauwi sa Earth ang isang alaga para sa treats',
 tut3_c='Magsisimula ka sa 4 na aso: kapag lahat ay umuwi sa Earth, tapos ang biyahe',
 tut3_c_cats='Magsisimula ka sa 4 na pusa: kapag lahat ay umuwi sa Earth, tapos ang biyahe',
 tut3_c_together='Magsisimula ka sa 4 na alaga: kapag lahat ay umuwi sa Earth, tapos ang biyahe',
 tut3_d='Pinupuno ng treats, pinupuno ng gates; inuubos ng {b}',
 dom_clone_line='Level labing-isa. Pagpupugay kay Weird Al Yankovic.',
 sr_gameover='Lahat ay lumipad pauwi sa Earth'),
'sv': dict(
 shade_charge='GODISLADDNING',
 title_dodge_p='Undvik bländet. Håll godisladdningen uppe.',
 title_dodge_l='Undvik bländet · håll godiset uppe',
 title_collect='Samla godis — håll GODISLADDNINGEN uppe',
 desk_dodge='Undvik bländet. Håll din godisladdning uppe.',
 fl_shade='+GODIS',
 fl_eaten='HEM TILL JORDEN! FLOCKEN VÄXER',
 tut2_a='Godisskålar fyller på din laddning',
 tut2_b='GODISLADDNINGEN tar slut = en hund flyger hem till Jorden efter mer godis',
 tut2_b_cats='GODISLADDNINGEN tar slut = en katt flyger hem till Jorden efter mer godis',
 tut2_b_together='GODISLADDNINGEN tar slut = ett husdjur flyger hem till Jorden efter mer godis',
 tut3_c='Du börjar med 4 hundar: när alla flyger hem till Jorden tar resan slut',
 tut3_c_cats='Du börjar med 4 katter: när alla flyger hem till Jorden tar resan slut',
 tut3_c_together='Du börjar med 4 husdjur: när alla flyger hem till Jorden tar resan slut',
 tut3_d='Godis fyller på, portar fyller; {b} förbrukar',
 dom_clone_line='Nivå elva. Vi lyfter på hatten för Weird Al Yankovic.',
 sr_gameover='Alla flög hem till Jorden'),
'ru': dict(
 shade_charge='ЗАРЯД ВКУСНЯШЕК',
 title_dodge_p='Уклоняйся от бликов. Держи заряд вкусняшек.',
 title_dodge_l='Уклоняйся · держи вкусняшки',
 title_collect='Собирай вкусняшки — держи ЗАРЯД ВКУСНЯШЕК',
 desk_dodge='Уклоняйся от бликов. Держи свой заряд вкусняшек.',
 fl_shade='+ВКУСНЯШКИ',
 fl_eaten='ДОМОЙ, НА ЗЕМЛЮ! СТАЯ РАСТЁТ',
 tut2_a='Миски со вкусняшками пополняют заряд',
 tut2_b='ЗАРЯД ВКУСНЯШЕК кончился = пёс летит домой на Землю за вкусняшками',
 tut2_b_cats='ЗАРЯД ВКУСНЯШЕК кончился = кот летит домой на Землю за вкусняшками',
 tut2_b_together='ЗАРЯД ВКУСНЯШЕК кончился = питомец летит домой на Землю за вкусняшками',
 tut3_c='У тебя 4 пса: когда все улетят домой на Землю, путешествие закончится',
 tut3_c_cats='У тебя 4 кота: когда все улетят домой на Землю, путешествие закончится',
 tut3_c_together='У тебя 4 питомца: когда все улетят домой на Землю, путешествие закончится',
 tut3_d='Вкусняшки пополняют, ворота заполняют; {b} тратит',
 dom_clone_line='Уровень одиннадцать. Снимаем шляпу перед Weird Al Yankovic.',
 sr_gameover='Все улетели домой на Землю'),
'uk': dict(
 shade_charge='ЗАРЯД СМАКОЛИКІВ',
 title_dodge_p='Ухиляйся від відблисків. Тримай заряд смаколиків.',
 title_dodge_l='Ухиляйся · тримай смаколики',
 title_collect='Збирай смаколики — тримай ЗАРЯД СМАКОЛИКІВ',
 desk_dodge='Ухиляйся від відблисків. Тримай свій заряд смаколиків.',
 fl_shade='+СМАКОЛИКИ',
 fl_eaten='ДОДОМУ, НА ЗЕМЛЮ! ЗГРАЯ РОСТЕ',
 tut2_a='Миски зі смаколиками поповнюють заряд',
 tut2_b='ЗАРЯД СМАКОЛИКІВ скінчився = пес летить додому на Землю по смаколики',
 tut2_b_cats='ЗАРЯД СМАКОЛИКІВ скінчився = кіт летить додому на Землю по смаколики',
 tut2_b_together='ЗАРЯД СМАКОЛИКІВ скінчився = улюбленець летить додому на Землю по смаколики',
 tut3_c='У тебе 4 пси: коли всі полетять додому на Землю, подорож закінчиться',
 tut3_c_cats='У тебе 4 коти: коли всі полетять додому на Землю, подорож закінчиться',
 tut3_c_together='У тебе 4 улюбленці: коли всі полетять додому на Землю, подорож закінчиться',
 tut3_d='Смаколики поповнюють, ворота наповнюють; {b} витрачає',
 dom_clone_line='Рівень одинадцять. Знімаємо капелюха перед Weird Al Yankovic.',
 sr_gameover='Усі полетіли додому на Землю'),
'ja': dict(
 shade_charge='おやつチャージ',
 title_dodge_p='まぶしい光をよけて。おやつチャージをキープ。',
 title_dodge_l='光をよけて · おやつをキープ',
 title_collect='おやつを集めて — おやつチャージをキープ',
 desk_dodge='まぶしい光をよけて。おやつチャージをキープしよう。',
 fl_shade='+おやつ',
 fl_eaten='地球におかえり！むれが大きくなる',
 tut2_a='おやつのお皿でチャージ回復',
 tut2_b='おやつチャージが切れる = 犬がおやつを取りに地球へ帰る',
 tut2_b_cats='おやつチャージが切れる = 猫がおやつを取りに地球へ帰る',
 tut2_b_together='おやつチャージが切れる = ペットがおやつを取りに地球へ帰る',
 tut3_c='犬4匹でスタート：みんな地球に帰ったら旅はおしまい',
 tut3_c_cats='猫4匹でスタート：みんな地球に帰ったら旅はおしまい',
 tut3_c_together='ペット4匹でスタート：みんな地球に帰ったら旅はおしまい',
 tut3_d='おやつで回復、ゲートで満タン；{b}で減る',
 dom_clone_line='レベル11。Weird Al Yankovic に脱帽。',
 sr_gameover='みんな地球に帰りました'),
'ko': dict(
 shade_charge='간식 충전',
 title_dodge_p='눈부신 빛을 피하세요. 간식 충전을 유지하세요.',
 title_dodge_l='빛 피하기 · 간식 유지',
 title_collect='간식 모으기 — 간식 충전 유지',
 desk_dodge='눈부신 빛을 피하세요. 간식 충전을 유지하세요.',
 fl_shade='+간식',
 fl_eaten='지구로 귀가! 무리가 커져요',
 tut2_a='간식 그릇이 충전을 채워요',
 tut2_b='간식 충전이 바닥나면 = 강아지가 간식을 가지러 지구로 돌아가요',
 tut2_b_cats='간식 충전이 바닥나면 = 고양이가 간식을 가지러 지구로 돌아가요',
 tut2_b_together='간식 충전이 바닥나면 = 반려동물이 간식을 가지러 지구로 돌아가요',
 tut3_c='강아지 4마리로 시작: 모두 지구로 돌아가면 여행이 끝나요',
 tut3_c_cats='고양이 4마리로 시작: 모두 지구로 돌아가면 여행이 끝나요',
 tut3_c_together='반려동물 4마리로 시작: 모두 지구로 돌아가면 여행이 끝나요',
 tut3_d='간식이 채우고, 게이트가 가득 채워요; {b}가 소모해요',
 dom_clone_line='레벨 11. Weird Al Yankovic에게 모자를 벗어 경의를.',
 sr_gameover='모두 지구로 돌아갔어요'),
'hi': dict(
 shade_charge='ट्रीट चार्ज',
 title_dodge_p='चमक से बचो। ट्रीट चार्ज बनाए रखो।',
 title_dodge_l='चमक से बचो · ट्रीट बनाए रखो',
 title_collect='ट्रीट इकट्ठा करो — ट्रीट चार्ज बनाए रखो',
 desk_dodge='चमक से बचो। अपना ट्रीट चार्ज बनाए रखो।',
 fl_shade='+ट्रीट',
 fl_eaten='घर, धरती की ओर! झुंड बढ़ा',
 tut2_a='ट्रीट के कटोरे चार्ज भरते हैं',
 tut2_b='ट्रीट चार्ज खत्म = एक कुत्ता और ट्रीट लेने धरती पर उड़ जाता है',
 tut2_b_cats='ट्रीट चार्ज खत्म = एक बिल्ली और ट्रीट लेने धरती पर उड़ जाती है',
 tut2_b_together='ट्रीट चार्ज खत्म = एक पालतू और ट्रीट लेने धरती पर उड़ जाता है',
 tut3_c='तुम 4 कुत्तों से शुरू करते हो: सब धरती लौट जाएँ तो सफ़र पूरा',
 tut3_c_cats='तुम 4 बिल्लियों से शुरू करते हो: सब धरती लौट जाएँ तो सफ़र पूरा',
 tut3_c_together='तुम 4 पालतुओं से शुरू करते हो: सब धरती लौट जाएँ तो सफ़र पूरा',
 tut3_d='ट्रीट भरते हैं, गेट पूरा भरते हैं; {b} खर्च करता है',
 dom_clone_line='लेवल ग्यारह। Weird Al Yankovic को टोपी उठाकर सलाम।',
 sr_gameover='सब धरती पर घर लौट गए'),
'th': dict(
 shade_charge='พลังขนม',
 title_dodge_p='หลบแสงจ้า รักษาพลังขนมไว้',
 title_dodge_l='หลบแสง · รักษาขนมไว้',
 title_collect='เก็บขนม — รักษาพลังขนมไว้',
 desk_dodge='หลบแสงจ้า รักษาพลังขนมของคุณไว้',
 fl_shade='+ขนม',
 fl_eaten='กลับบ้านที่โลก! ฝูงโตขึ้น',
 tut2_a='ชามขนมเติมพลังขนม',
 tut2_b='พลังขนมหมด = น้องหมาบินกลับโลกไปเอาขนมเพิ่ม',
 tut2_b_cats='พลังขนมหมด = น้องแมวบินกลับโลกไปเอาขนมเพิ่ม',
 tut2_b_together='พลังขนมหมด = สัตว์เลี้ยงบินกลับโลกไปเอาขนมเพิ่ม',
 tut3_c='เริ่มด้วยน้องหมา 4 ตัว: เมื่อทุกตัวบินกลับโลก การเดินทางก็จบ',
 tut3_c_cats='เริ่มด้วยน้องแมว 4 ตัว: เมื่อทุกตัวบินกลับโลก การเดินทางก็จบ',
 tut3_c_together='เริ่มด้วยสัตว์เลี้ยง 4 ตัว: เมื่อทุกตัวบินกลับโลก การเดินทางก็จบ',
 tut3_d='ขนมเติมพลัง ประตูเติมเต็ม; {b} ใช้พลัง',
 dom_clone_line='เลเวลสิบเอ็ด ขอถอดหมวกให้ Weird Al Yankovic',
 sr_gameover='ทุกตัวบินกลับบ้านที่โลกแล้ว'),
}
ALL = {'diff_eleven': '11 · ★ · {m}'}
p = '/workspace/cat-mode/src/i18n.ts'
src = open(p, encoding='utf-8').read()
lines = src.split('\n')
# find language blocks
starts = {}
for i, l in enumerate(lines):
    m = re.match(r'^const (\w+)(?:: Record<Key, string>)? = \{$', l)
    if m: starts[m.group(1)] = i
missing = []
def q(v):
    return "'" + v.replace('\\', '\\\\').replace("'", "\\'") + "'"
for lang, vals in T.items():
    if lang not in starts: missing.append(('lang', lang)); continue
    i0 = starts[lang]
    i1 = i0 + 1
    while lines[i1] != '};': i1 += 1
    allv = {**vals, **ALL}
    for k, v in allv.items():
        found = False
        for j in range(i0, i1):
            if re.match(r'^  ' + k + r': ', lines[j]):
                # single-line values only
                lines[j] = f'  {k}: {q(v)},'
                found = True
                break
        if not found: missing.append((lang, k))
open(p, 'w', encoding='utf-8').write('\n'.join(lines))
print('missing:', missing)
print('langs:', sorted(starts))
