/**
 * The playful G-rated taunt line on the leaderboard (game-over) screen.
 *
 * Shown to everyone who isn't #1 on the board they just played for: one set of lines for runs that
 * missed the board, another for runs on the board below #1. Original slapstick, all four languages,
 * the same count per language so one random pick works in any language. #1 gets no taunt.
 */
import type { Lang } from '../i18n';

const MISSED: Record<Lang, readonly string[]> = {
  en: [
    'THE BOARD SAVED YOU A SEAT. IT\'S IN THE PARKING LOT.',
    'SO CLOSE! THE TOP 11 CAN HEAR YOU KNOCKING.',
    'YOUR SCORE IS ON ITS WAY. IT STOPPED FOR SNACKS.',
    'THE BOARD SLIPPED ON A BANANA PEEL RIGHT BEFORE YOU ARRIVED.',
    'ONE MORE RIDE AND THE BOARD MIGHT HAVE TO SCOOT OVER.',
    'THE TOP 11 LOCKED THE DOOR. THE WINDOW IS WIDE OPEN.',
  ],
  es: [
    'LA TABLA TE GUARDÓ UN ASIENTO. ESTÁ EN EL ESTACIONAMIENTO.',
    '¡CASI! EL TOP 11 YA TE OYE TOCAR LA PUERTA.',
    'TU RÉCORD VIENE EN CAMINO. PARÓ A COMPRAR BOCADILLOS.',
    'LA TABLA PISÓ UNA CÁSCARA DE PLÁTANO JUSTO ANTES DE QUE LLEGARAS.',
    'UNA VUELTA MÁS Y LA TABLA TENDRÁ QUE HACERTE SITIO.',
    'EL TOP 11 CERRÓ LA PUERTA. LA VENTANA ESTÁ ABIERTA.',
  ],
  vi: [
    'BẢNG ĐÃ GIỮ CHỖ CHO BẠN. CHỖ ĐÓ Ở BÃI ĐỖ XE.',
    'SUÝT NỮA! TOP 11 ĐÃ NGHE THẤY BẠN GÕ CỬA.',
    'ĐIỂM CỦA BẠN ĐANG TỚI. NÓ GHÉ MUA ĐỒ ĂN VẶT.',
    'BẢNG VỪA GIẪM VỎ CHUỐI NGAY TRƯỚC KHI BẠN TỚI.',
    'THÊM MỘT LƯỢT NỮA LÀ BẢNG PHẢI NHÍCH QUA CHO BẠN.',
    'TOP 11 KHÓA CỬA RỒI. CỬA SỔ VẪN MỞ TOANG.',
  ],
  zh: [
    '排行榜给你留了个座位，在停车场。',
    '就差一点！前 11 名已经听到你在敲门了。',
    '你的分数正在路上，它停下来买零食了。',
    '你来之前，排行榜刚好踩到了香蕉皮。',
    '再骑一次，排行榜就得给你挪位置了。',
    '前 11 名锁上了门，可窗户还开着呢。',
  ],

  fr: [
    'LE CLASSEMENT T’A GARDÉ UNE PLACE. ELLE EST SUR LE PARKING.',
    'SI PRÈS ! LE TOP 11 T’ENTEND TOQUER.',
    'TON SCORE EST EN ROUTE. IL S’EST ARRÊTÉ POUR DES ENCAS.',
    'LE CLASSEMENT A GLISSÉ SUR UNE PEAU DE BANANE JUSTE AVANT TOI.',
    'ENCORE UN TOUR ET LE CLASSEMENT DEVRA SE POUSSER.',
    'LE TOP 11 A VERROUILLÉ LA PORTE. LA FENÊTRE EST GRANDE OUVERTE.',
  ],
  de: [
    'DIE LISTE HAT DIR EINEN PLATZ FREIGEHALTEN. AUF DEM PARKPLATZ.',
    'SO NAHE! DIE TOP 11 HÖREN DICH KLOPFEN.',
    'DEIN SCORE IST UNTERWEGS. ER HAT FÜR SNACKS ANGEHALTEN.',
    'DIE LISTE IST AUF EINER BANANENSCHALE AUSGERUTSCHT — GERADE VOR DIR.',
    'NOCH EINE RUNDE UND DIE LISTE MUSS PLATZ MACHEN.',
    'DIE TOP 11 HABEN DIE TÜR ZU. DAS FENSTER IST WEIT OFFEN.',
  ],
  pt: [
    'O PLACAR GUARDOU SEU LUGAR. ESTÁ NO ESTACIONAMENTO.',
    'QUASE! O TOP 11 JÁ TE OUVIU BATER.',
    'SEU PLACAR ESTÁ A CAMINHO. PAROU PARA LANCHAR.',
    'O PLACAR ESCORREGOU NA CASCA DE BANANA LOGO ANTES DE VOCÊ.',
    'MAIS UMA VOLTA E O PLACAR VAI TER QUE SE AFASTAR.',
    'O TOP 11 TRANCOU A PORTA. A JANELA ESTÁ ABERTA.',
  ],
  it: [
    'LA CLASSIFICA TI HA TENUTO UN POSTO. È NEL PARCHEGGIO.',
    'QUASI! IL TOP 11 TI SENTE BUSSARE.',
    'IL TUO PUNTEGGIO È IN ARRIVO. SI È FERMATO PER UNO SNACK.',
    'LA CLASSIFICA È SCIVOLATA SU UNA BUCCIA DI BANANA PROPRIO PRIMA DI TE.',
    'UN GIRO IN PIÙ E LA CLASSIFICA DOVRÀ FARTI SPAZIO.',
    'IL TOP 11 HA CHIUSO LA PORTA. LA FINESTRA È SPALANCATA.',
  ],
  nl: [
    'HET BORD HEEFT EEN PLEK VOOR JE BEWAARD. OP DE PARKING.',
    'ZO DICHTBIJ! DE TOP 11 HOORT JE KLOPPEN.',
    'JE SCORE IS ONDERWEG. HIJ STOPTE VOOR SNACKS.',
    'HET BORD GLEED UIT OVER EEN BANANENSCHIL NET VOOR JOU.',
    'NOG ÉÉN RIT EN HET BORD MOET OPSCHUIVEN.',
    'DE TOP 11 DEED DE DEUR OP SLOT. HET RAAM STAAT WIJD OPEN.',
  ],
  pl: [
    'TABLICA ZOSTAWIŁA CI MIEJSCE. NA PARKINGU.',
    'PRAWIE! TOP 11 SŁYSZY, JAK PUKASZ.',
    'TWÓJ WYNIK JEST W DRODZE. ZATRZYMAŁ SIĘ PO PRZEKĄSKĘ.',
    'TABLICA POŚLIZGNĘŁA SIĘ NA SKÓRCE BANANA TUŻ PRZED TOBĄ.',
    'JESZCZE JEDEN PRZEJAZD I TABLICA MUSI SIĘ PRZESUNĄĆ.',
    'TOP 11 ZAMKNĄŁ DRZWI. OKNO STOI OTWOREM.',
  ],
  tr: [
    'TABLO SANA YER AYIRDI. OTOPARKTA.',
    'NEREDEYSE! İLK 11 SENİ KAPIDA DUYUYOR.',
    'SKORUN YOLDA. ATISTIRMAYA UĞRADI.',
    'TABLO TAM SEN GELMEDEN MUZ KABUĞUNA KAYDI.',
    'BİR TUR DAHA VE TABLO KAYMAK ZORUNDA KALACAK.',
    'İLK 11 KAPİYİ KİLİTLEDİ. PENCERE AÇIK.',
  ],
  id: [
    'PAPAN MENYIMPAN KURSIMU. DI PARKIRAN.',
    'NYARIS! TOP 11 SUDAH MENDENGAR KETUKANMU.',
    'SKORMU SEDANG MENUJU. BERHENTI BELI CAMILAN.',
    'PAPAN TERSELESET KULIT PISANG TEPAT SEBELUM KAMU DATANG.',
    'SATU PUTARAN LAGI DAN PAPAN HARUS MENGESAMPING.',
    'TOP 11 MENGUNCI PINTU. JENDELA TERBUKA LEBAR.',
  ],
  fil: [
    'MAY INILAGAY NA UPUAN PARA SA’YO ANG BOARD. NASA PARKING LOT.',
    'HALOS! NARIRINIG KA NA NG TOP 11 NA KUMKATOK.',
    'PAPARATING ANG ISKOR MO. HUMINTO PARA SA MERYENDA.',
    'NADULAS ANG BOARD SA BALAT NG SAGING BAGO KA DUMATING.',
    'ISANG BIYAHE PA AT KAILANGANG LUMAYO ANG BOARD.',
    'IKINANDADO NG TOP 11 ANG PINTO. BUKAS ANG BINTANA.',
  ],
  sv: [
    'LISTAN SPARADE EN PLATS ÅT DIG. PÅ PARKERINGEN.',
    'SÅ NÄRA! TOPP 11 HÖR DIG KNAKA.',
    'DIN POÄNG ÄR PÅ VÄG. DEN STANNADE FÖR SNACKS.',
    'LISTAN HALKADE PÅ ETT BANANSKAL JUST FÖRE DIG.',
    'EN RUNDA TILL OCH LISTAN MÅSTE FLYTTA PÅ SIG.',
    'TOPP 11 LÅSTE DÖRREN. FÖNSTRET ÄR VIDÖPPET.',
  ],
};

const BELOW_TOP: Record<Lang, readonly string[]> = {
  en: [
    'ON THE BOARD! #1 IS NERVOUSLY POLISHING ITS TROPHY.',
    'NICE! #1 JUST SPILLED ITS LEMONADE LOOKING AT YOU.',
    '#1 CHECKED ITS MIRRORS. YOU\'RE IN THEM.',
    'THE TOP SPOT IS STILL WARM. SOMEONE JUST STOOD UP.',
    '#1 HAS STARTED WEARING A HELMET. JUST IN CASE.',
    'YOU\'RE CLIMBING! #1 IS HIDING THE LADDER.',
  ],
  es: [
    '¡EN LA TABLA! EL #1 PULE SU TROFEO MUY NERVIOSO.',
    '¡BIEN! AL #1 SE LE CAYÓ LA LIMONADA AL VERTE.',
    'EL #1 MIRÓ SUS ESPEJOS. AHÍ ESTÁS TÚ.',
    'EL PRIMER PUESTO SIGUE CALIENTITO. ALGUIEN SE ACABA DE LEVANTAR.',
    'EL #1 YA SE PUSO CASCO. POR SI ACASO.',
    '¡VAS SUBIENDO! EL #1 ESTÁ ESCONDIENDO LA ESCALERA.',
  ],
  vi: [
    'CÓ TÊN TRÊN BẢNG! HẠNG 1 ĐANG LO LẮNG LAU CÚP.',
    'HAY LẮM! HẠNG 1 VỪA LÀM ĐỔ LY NƯỚC CHANH KHI THẤY BẠN.',
    'HẠNG 1 NHÌN GƯƠNG CHIẾU HẬU. BẠN ĐANG Ở TRONG ĐÓ.',
    'GHẾ HẠNG 1 VẪN CÒN ẤM. CÓ NGƯỜI VỪA ĐỨNG DẬY.',
    'HẠNG 1 BẮT ĐẦU ĐỘI MŨ BẢO HIỂM. CHO CHẮC.',
    'BẠN ĐANG LEO LÊN! HẠNG 1 ĐANG GIẤU CÁI THANG.',
  ],
  zh: [
    '上榜了！第 1 名正紧张地擦奖杯。',
    '漂亮！第 1 名看到你，柠檬水都洒了。',
    '第 1 名看了看后视镜，里面是你。',
    '第一名的座位还热乎着，有人刚站起来。',
    '第 1 名开始戴头盔了，以防万一。',
    '你在往上爬！第 1 名正在藏梯子。',
  ],

  fr: [
    'AU CLASSEMENT ! LE N°1 POLIT SON TROPHÉE NERVEUSEMENT.',
    'BIEN JOUÉ ! LE N°1 A RENVERSÉ SA LIMONADE EN TE VOYANT.',
    'LE N°1 A REGARDÉ SES RÉTROVISEURS. TU Y ES.',
    'LA PREMIÈRE PLACE EST ENCORE CHAUDE. QUELQU’UN VIENT DE SE LEVER.',
    'LE N°1 A MIS UN CASQUE. AU CAS OÙ.',
    'TU GRIMPES ! LE N°1 CACHE L’ÉCHELLE.',
  ],
  de: [
    'AUF DER LISTE! #1 POLIERT NERVÖS SEINEN POKAL.',
    'TOLLI! #1 HAT SEINE LIMONADE VERSCHÜTTET, ALS ES DICH SAH.',
    '#1 HAT IN DIE SPIEGEL GESCHAUT. DU BIST DRAN.',
    'PLATZ 1 IST NOCH WARM. JEMAND IST GERADE AUFGESTANDEN.',
    '#1 TRÄGT JETZT EINEN HELM. NUR FÜR ALLE FÄLLE.',
    'DU KLETTERST! #1 VERSTECKT DIE LEITER.',
  ],
  pt: [
    'NO PLACAR! O #1 ESTÁ NERVOSO POLINDO O TROFÉU.',
    'BOA! O #1 DERRAMOU A LIMONADA AO TE VER.',
    'O #1 OLHOU OS ESPELHOS. VOCÊ ESTÁ NELES.',
    'O 1º LUGAR AINDA ESTÁ QUENTE. ALGUÉM ACABOU DE SE LEVANTAR.',
    'O #1 COMEÇOU A USAR CAPACETE. POR PRECAUÇÃO.',
    'VOCÊ ESTÁ SUBINDO! O #1 ESTÁ ESCONDENDO A ESCADA.',
  ],
  it: [
    'IN CLASSIFICA! IL #1 STA LUCIDANDO IL TROFEO NERVOSSO.',
    'BELLO! IL #1 HA VERSATO LA LIMONATA VEDENDOTI.',
    'IL #1 HA CONTROLLATO GLI SPECCHIETTI. CI SEI TU.',
    'IL PRIMO POSTO È ANCORA CALDO. QUALCUNO SI È APPENA ALZATO.',
    'IL #1 HA INIZIATO A INDOSSARE UN CASCO. PER SICUREZZA.',
    'STAI SALENDO! IL #1 STA NASCONDENDO LA SCALA.',
  ],
  nl: [
    'OP HET BORD! #1 POETST ZENUWACHTIG ZIJN TROFEE.',
    'MOOI! #1 MORSTE ZIJN LIMONADE TOEN HIJ JE ZAG.',
    '#1 KEEK IN DE SPIEGELS. JIJ STAAT ERIN.',
    'PLEK 1 IS NOG WARM. IEMAND STOND NET OP.',
    '#1 DRAAGT NU EEN HELM. VOOR HET GEVAL.',
    'JE KLIMT! #1 VERBERGT DE LADDER.',
  ],
  pl: [
    'NA TABLICY! #1 NERWOWO POLERUJE PUCHAR.',
    'SUPER! #1 ROZLAŁ LEMONIADĘ, WIDZĄC CIĘ.',
    '#1 SPOJRZAŁ W LUSTERKA. JESTEŚ W NICH.',
    'PIERWSZE MIEJSCE JESZCZE CIEPŁE. KTOŚ WŁAŚNIE WSTAŁ.',
    '#1 ZAŁOŻYŁ KASK. NA WSZELKI WYPADEK.',
    'WSPINASZ SIĘ! #1 CHOWA DRABINĘ.',
  ],
  tr: [
    'TABLODA! #1 GERGİNCE KUPASINI PARLATIYOR.',
    'GÜZEL! #1 SENİ GÖRÜNCE LİMONATASINI DÖKTÜ.',
    '#1 AYNALARA BAKTI. SENDESİN.',
    '1. YER HÂLÂ SICAK. BİRİ YENİ KALKTI.',
    '#1 KASK TAKMAYA BAŞLADI. NE OLUR NE OLMAZ.',
    'TIRMANIYORSUN! #1 MERDİVENİ GİZLIYOR.',
  ],
  id: [
    'DI PAPAN! #1 GUGUP MEMOLES TROFINYA.',
    'BAGUS! #1 TUMPAH LIMUN SAAT MELIHATMU.',
    '#1 MEMERIKSA SPION. KAMU ADA DI SITU.',
    'TEMPAT 1 MASIH HANGAT. SESEORANG BARU BERDIRI.',
    '#1 MULAI MEMAKAI HELM. JAGA-JAGA.',
    'KAMU MENDAKI! #1 MENYEMBUNYIKAN TANGGA.',
  ],
  fil: [
    'NASA BOARD! KINAKABAHAN ANG #1 SA PAGKIINIS NG TROPHY.',
    'AYOS! NATAPON ANG LIMONADA NG #1 NANG MAKITA KA.',
    'TUMINGIN ANG #1 SA MGA SALAMIN. NASA LOOB KA.',
    'MAINIT PA ANG UNANG UPUAN. KAKATAYO LANG NG ISANG TAO.',
    'NAGSISIMULA ANG #1 MAGSUOT NG HELMET. PARA SIGURADO.',
    'UMAAKYAT KA! ITINATAGO NG #1 ANG HAGDAN.',
  ],
  sv: [
    'PÅ LISTAN! #1 PUTSAR NERVÖST SIN POKAL.',
    'BRA! #1 SPILLDE SIN LEMONAD NÄR HEN SÅG DIG.',
    '#1 KOLLADE SPEGLARNA. DU ÄR I DEM.',
    'FÖRSTA PLATSEN ÄR FORTFARANDE VARM. NÅGON RESTE SIG JUST.',
    '#1 HAR BÖRJAT BÄRA HJÄLM. FÖR SÄKERHETS SKULL.',
    'DU KLÄTTRAR! #1 GÖMMER STEGEN.',
  ],
};

/** Lines per set (same in every language). */
export const BOARD_TAUNT_COUNT = MISSED.en.length;

/**
 * The line for this viewer: `place` is their index on the board (-1 = not on it). #1 (place 0)
 * and empty boards get ''. `pick` is any integer (chosen once per game-over screen).
 */
export function boardTaunt(l: Lang, place: number, pick: number, boardSize: number): string {
  if (place === 0 || boardSize <= 0) return '';
  const set = (place < 0 ? MISSED : BELOW_TOP)[l] ?? (place < 0 ? MISSED : BELOW_TOP).en;
  return set[((pick % set.length) + set.length) % set.length];
}
